javax:
  sql:
    DataSource:
      principal:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          url: jdbc:postgresql://localhost:5432/distribuida
          user: postgres
          password: postgres
